#!/bin/bash
yay -Sy \
neofetch \
neovim \
htop \
polkit \
rofi \
dmenu \
catfish \
ranger \
flameshot-git \
pamac-aur \
archlinux-logout-git \
archlinux-logout-themes-git \
sddm \
pipewire \
wayfire \
waybar \
swaybg \
wofi \
swaylock \
lightdm \
bemenu \
wlogout \
xorg \
thunar \
konsole \
dolphin \
variety \
feh \
i3 \
i3-gaps \
picom \
autotiling \
network-manager-applet \
numlockx \
xfce4 \
xfce4-goodies \
conky \
blueberry \
volumeicon \
alacritty \
network-manager-applet \
fcitx5-im \
fcitx5-chinese-addons \
fcitx5-pinyin-zhwiki \
fcitx5-material-color \
adobe-source-han-sans-cn-fonts \
adobe-source-han-sans-tw-fonts \
adobe-source-han-sans-hk-fonts \
adobe-source-han-serif-cn-fonts \
adobe-source-han-serif-tw-fonts \
adobe-source-han-serif-hk-fonts \
noto-fonts-sc \
noto-fonts-tc \
ttf-jetbrains-mono \
nerd-fonts-jetbrains-mono \
wqy-microhei \
wqy-zenhei \
wqy-bitmapfont \
ttf-arphic-ukai \
ttf-arphic-uming \
opendesktop-fonts \
noto-fonts-emoji \
wps-office \
wps-office-mui-zh-cn \
ttf-wps-fonts \
netease-cloud-music \
visual-studio-code-bin \
deepin-wine-tim \
deepin-wine-wechat \
microsoft-edge-dev-bin \
firefox \

